### ISSUE TITLE
Status Request / One more doubt

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#12]
Could you please remove the "RKIT DEBUG" message "reviving at x seconds"

i would like to keep the "reviving" message from the plugin and maybe add another print like " revived successfully"

Do you plan to publish this on alliedmodders for everyone to use?

**Comment by AoiKagase** [comment]
> Could you please remove the "RKIT DEBUG" message "reviving at x seconds"

Oh sorry. removing soon.

> i would like to keep the "reviving" message from the plugin and maybe add another print like " revived successfully"

hm, Let's adjust it.

> Do you plan to publish this on alliedmodders for everyone to use?

No. 
I've already published some new plugins here, but I won't post them to the forum anew.
I don't post them in the forum because they are unlikely to be approved and I don't have the time to deal with bugs and requests.
I also don't want to have to report more bugs caused by non-Steam.

**Comment by eflernicolas** [comment]
Thanks so much for all this
