### ISSUE TITLE
Bug - Bot Corpses not disappearing after death

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#22]
usually corpses fade away but with the last version they stay in the server forever.

**Comment by AoiKagase** [comment]
What cvars are you setting?

**Comment by eflernicolas** [comment]
rkit_health 50
rkit_cost 0
rkit_screen_fade 0
rkit_screen_fade_time 0
rkit_delay_revive 0
rkit_delay_die 0
rkit_deathmatch 0
rkit_bot_has_kit 0
rkit_bot_can_revive 0
rkit_buy_mode 0
rkit_buy_zone 0
rkit_distance 200.0
rkit_check_obstacle 0
rkit_reward 0
rkit_revive_radius 20.0
rkit_revive_attempt 10
rkit_revive_move_lock 0

**Comment by eflernicolas** [comment]
last update makes ct corpses ghosts appear  in terrorist base  sometimes. Try pool day for example.

**Comment by AoiKagase** [comment]
If rkit_delay_die 0, the corpse never disappears because the resurrection time is infinite.

**Comment by AoiKagase** [comment]
> last update makes ct corpses ghosts appear in terrorist base sometimes. Try pool day for example.

Please do not update after 2640e61 as I think there is still a problem.

**Comment by AoiKagase** [comment]
This is a fairly esoteric bug.
If rkit_delay_die is set to 5 seconds or more, the corpse is deleted correctly, but if it is less than that, the corpse remains for some reason.
If rkit_delay_die is set to 0 seconds, the corpse is not deleted because the resuscitation time is infinite. This is the correct behavior.

**Comment by eflernicolas** [comment]
> This is a fairly esoteric bug. If rkit_delay_die is set to 5 seconds or more, the corpse is deleted correctly, but if it is less than that, the corpse remains for some reason. If rkit_delay_die is set to 0 seconds, the corpse is not deleted because the resuscitation time is infinite. This is the correct behavior.

That make sense except rkit_delay_die should cancel out if  rkit_bot_can_revive 0, but corpses of bots still remain.

bots and players used to disappear till one of your last updates.  

if you can fix that great, it has not been performance impacting my server luckily.

**Comment by AoiKagase** [comment]
Fixed.
rkit_delay_die The bug where the corpse does not disappear for less than 5 is still there.

**Comment by eflernicolas** [comment]
Error is indeed fixed.  are you forcing corpses to disappear? they used to blend into the floor like in vanilla CS and now they instantly disappear after 4 sec aprox.
Just a curious, that doesn't represent any load to the server?

**Comment by AoiKagase** [comment]
On a more technical note.
The default corpse logic is executed after the ClCorpse message is issued and executed after the death animation ends, not at the actual death.
(This would be the process of leaving the actual corpse and later blending it with the floor.)
Since we blocked the ClCorpse message, the default corpse process is no longer performed at all, and the server load will be slightly reduced.
